apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: go-app
  template:
    metadata:
      labels:
        app: go-app
    spec:
      containers:
      - name: go
        image: docker.io/julendk/go-server:latest  # <- Tekton actualizará este tag
        ports:
        - containerPort: 8080
